#pragma once

/* */
enum class LayoutTypes
{
	LAYOUT_OVERLAY, 
	LAYOUT_DEFAULT,
	LAYOUT_PARTICLECLOUD,
	LAYOUT_PARTICLECLOUD_DEPTH,
	LAYOUT_PARTICLECLOUD_OPACITY,
	LAYOUT_PARTICLECLOUD_SO,
	LAYOUT_PARTICLECLOUD_FINAL,
	LAYOUT_TEXT, 
	LAYOUT_SKY,
	LAYOUT_SUN,
	LAYOUT_BASIC_PARTICLE,
	LAYOUT_ENERGY_PARTICLE,
	LAYOUT_DRAIN_PARTICLE,
	LAYOUT_CELESTIAL,
	LAYOUT_GRASS,
	LAYOUT_VERTEXID,
	LAYOUT_ANIMATION,
	LAYOUT_MODEL_INSTANCED,
	LAYOUT_FINAL,
	LAYOUT_POSITION,
	LAYOUT_1FLOAT,
	LAYOUT_SURFACE_INSTANCED,
	LAYOUT_PARTICLE,
	LAYOUT_AMOUNT
};

#define	SAFE_RELEASE(x)	if( x ) { (x)->Release();	(x) = NULL; }
#define	SAFE_DELETE(x)	if( x ) { delete(x);	(x) = NULL; }
